server:
  port: 8001
spring:
  application:
    name: cloud-payment-service-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a_little_demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.cloud.zeman
    configuration:
      map-underscore-to-camel-case: true